# fix-encoding-mojibake.ps1 — Repara tildes/eñes destruidas a '?' por una escritura ASCII previa.
# Reemplazo por palabra EXACTA (case-sensitive), nunca sobre '?' sueltos: no toca URLs ni query strings.

$ErrorActionPreference = 'Stop'
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

$pairs = @(
  @('Lead?Visita?Cierre', 'Lead→Visita→Cierre'),
  @('?Quer?s', '¿Querés'),
  @('?C?mo', '¿Cómo'),
  @('Lead?Cierre', 'Lead→Cierre'),
  @('Contrase?a', 'Contraseña'),
  @('autom?ticamente', 'automáticamente'),
  @('caracter?sticas', 'características'),
  @('satisfacci?n', 'satisfacción'),
  @('din?micamente', 'dinámicamente'),
  @('estrat?gicas', 'estratégicas'),
  @('Sincronizaci?n', 'Sincronización'),
  @('Configuraci?n', 'Configuración'),
  @('Estad?sticas', 'Estadísticas'),
  @('comunicaci?n', 'comunicación'),
  @('actualizar?n', 'actualizarán'),
  @('ACEPTACI?N', 'ACEPTACIÓN'),
  @('Estad?stica', 'Estadística'),
  @('Navegaci?n', 'Navegación'),
  @('Supervisi?n', 'Supervisión'),
  @('Coordinaci?n', 'Coordinación'),
  @('Producci?n', 'Producción'),
  @('Descripci?n', 'Descripción'),
  @('conversaci?n', 'conversación'),
  @('Ubicaci?n', 'Ubicación'),
  @('Operaci?n', 'Operación'),
  @('Comisi?n', 'Comisión'),
  @('Acci?n', 'Acción'),
  @('Tasaci?n', 'Tasación'),
  @('Gesti?n', 'Gestión'),
  @('M?dulo', 'Módulo'),
  @('m?dulos', 'módulos'),
  @('Tel?fono', 'Teléfono'),
  @('P?gina', 'Página'),
  @('t?tulo', 'título'),
  @('Condici?n', 'Condición'),
  @('invitaci?n', 'invitación'),
  @('renovaci?n', 'renovación'),
  @('Conexi?n', 'Conexión'),
  @('publicaci?n', 'publicación'),
  @('Difusi?n', 'Difusión'),
  @('biograf?a', 'biografía'),
  @('Cont?ctanos', 'Contáctanos'),
  @('Detecci?n', 'Detección'),
  @('Evoluci?n', 'Evolución'),
  @('Auditor?a', 'Auditoría'),
  @('Direcci?n', 'Dirección'),
  @('Cl?usulas', 'Cláusulas'),
  @('Par?metro', 'Parámetro'),
  @('Matr?culas', 'Matrículas'),
  @('Matr?cula', 'Matrícula'),
  @('Anomal?as', 'Anomalías'),
  @('T?rminos', 'Términos'),
  @('autom?ticos', 'automáticos'),
  @('autom?tico', 'automático'),
  @('Cr?ticas', 'Críticas'),
  @('Cr?tica', 'Crítica'),
  @('Inversi?n', 'Inversión'),
  @('inversi?n', 'inversión'),
  @('Cotizaci?n', 'Cotización'),
  @('Conversi?n', 'Conversión'),
  @('An?lisis', 'Análisis'),
  @('Reuni?n', 'Reunión'),
  @('M?trica', 'Métrica'),
  @('c?rdoba', 'córdoba'),
  @('C?rdoba', 'Córdoba'),
  @('Mart?nez', 'Martínez'),
  @('Atenci?n', 'Atención'),
  @('Sof?a', 'Sofía'),
  @('P?rez', 'Pérez'),
  @('G?mez', 'Gómez'),
  @('Galp?n', 'Galpón'),
  @('Bot?n', 'Botón'),
  @('M?nimo', 'Mínimo'),
  @('M?ximo', 'Máximo'),
  @('m?nima', 'mínima'),
  @('S?bados', 'Sábados'),
  @('cat?logos', 'catálogos'),
  @('Cat?logo', 'Catálogo'),
  @('PADR?N', 'PADRÓN'),
  @('C?digo', 'Código'),
  @('D?as', 'Días'),
  @('D?a', 'Día'),
  @('a?os', 'años'),
  @('A?o', 'Año'),
  @('Ba?os', 'Baños'),
  @('N?meros', 'Números'),
  @('Im?genes', 'Imágenes'),
  @('m?s', 'más'),
  @('sesi?n', 'sesión'),
  @('L?nea', 'Línea'),
  @('inc?gnita', 'incógnita'),
  @('pol?tica', 'política'),
  @('Raz?n', 'Razón'),
  @('le?do', 'leído'),
  @('le?da', 'leída'),
  @('Inter?s', 'Interés'),
  @('pod?s', 'podés'),
  @('est?s', 'estás'),
  @('vac?o', 'vacío'),
  @('Obt?n', 'Obtén'),
  @('f?brica', 'fábrica'),
  @('pr?ximo', 'próximo'),
  @('secci?n', 'sección'),
  @('cat?logo', 'catálogo'),
  @('r?gimen', 'régimen'),
  @('est?ndar', 'estándar'),
  @('Opci?n', 'Opción'),
  @('p?blico', 'público'),
  @('D?lares', 'Dólares'),
  @('t?cnicas', 'técnicas'),
  @('C?mo', 'Cómo'),
  @('S?b', 'Sáb'),
  @('T?tulo', 'Título'),
  @('contrase?a', 'contraseña'),
  @('p?gina', 'página'),
  @('operaci?n', 'operación'),
  @('Invitaci?n', 'Invitación'),
  @('d?as', 'días'),
  @('Estrat?gicas', 'Estratégicas'),
  @('Padr?n', 'Padrón'),
  @('l?nea', 'línea'),
  @('M?s', 'Más'),
  @('Pol?tica', 'Política'),
  @('Duraci?n', 'Duración'),
  @('AUDITOR?A', 'AUDITORÍA'),
  @('sincronizaci?n', 'sincronización'),
  @('lead?cierre', 'lead→cierre'),
  @('acci?n', 'acción'),
  @('Sesi?n', 'Sesión'),
  @('M?DULOS', 'MÓDULOS'),
  @('evoluci?n', 'evolución'),
  @('tel?fono', 'teléfono'),
  @('descripci?n', 'descripción'),
  @('CONFIGURACI?N', 'CONFIGURACIÓN'),
  @('ANOMAL?AS', 'ANOMALÍAS'),
  @('c?digo', 'código'),
  @('ESTAD?STICAS', 'ESTADÍSTICAS'),
  @('tasaci?n', 'tasación'),
  @('m?dulo', 'módulo'),
  @('CONTRASE?A', 'CONTRASEÑA'),
  @('INVITACI?N', 'INVITACIÓN')
)

$files = @('admin.html', 'assets/js/admin-app.js')
foreach ($f in $files) {
  $path = Join-Path $PSScriptRoot '..' | Join-Path -ChildPath $f
  $txt = [IO.File]::ReadAllText($path)
  $hitCount = 0
  foreach ($p in $pairs) {
    $n = ([regex]::Matches($txt, [regex]::Escape($p[0]))).Count
    if ($n -gt 0) { $txt = $txt.Replace($p[0], $p[1]); $hitCount += $n }
  }
  [IO.File]::WriteAllText($path, $txt, $utf8NoBom)
  Write-Output "$f : $hitCount reemplazos"
}

# Verificación: qué '?...' entre letras quedó (idealmente solo URLs/query strings)
foreach ($f in $files) {
  $path = Join-Path $PSScriptRoot '..' | Join-Path -ChildPath $f
  $txt = [IO.File]::ReadAllText($path)
  $m = [regex]::Matches($txt, '[A-Za-zÁÉÍÓÚÑáéíóúñü]\?[A-Za-zÁÉÍÓÚÑáéíóúñü]')
  Write-Output ("RESTANTES en {0}: {1} (deben ser solo ?v=, watch?v=, etc.)" -f $f, $m.Count)
}
